# FROM python:3
# COPY ./requirements.txt /requirements.txt
# WORKDIR /
# RUN pip install -r requirements.txt
# COPY . /
FROM python:3.8-slim-buster
WORKDIR /python-docker 
#WORKDIR /python-docker  задаёт рабочую директорию для следующей инструкции

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .
#CMD [ "python3", "app1.py"] описывает команду с аргументами, которую нужно выполнить когда контейнер будет запущен. Аргументы могут быть переопределены при запуске контейнера
CMD [ "python3", "app1.py"]